[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_project = "AiYexktgCp74R5aUCwDh6T8yaXC2doZXEEgQdKV7jBmG"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/a1111/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
